name: Braindump
author: Thierry Joyal
description: Collection of personal notes and opinions

avatar: https://avatars.githubusercontent.com/u/207902

footer-links:
  email:
  github: tjoyal
  linkedin: thierryjoyal
  rss: true
  twitter:

google_analytics: G-L8JG1KV5RS

url: https://blog.tjoyal.dev

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: expanded

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
